/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst";
export {};
import "sst";
declare module "sst" {
  export interface Resource {
    GithubClientID: {
      type: "sst.sst.Secret";
      value: string;
    };
    GithubClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientID: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    ResendApiKey: {
      type: "sst.sst.Secret";
      value: string;
    };
    Static: {
      type: "sst.cloudflare.StaticSite";
      url: string;
    };
  }
}
// cloudflare
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    CloudflareAuth: cloudflare.Service;
    CloudflareAuthKV: cloudflare.KVNamespace;
    Emails: cloudflare.Service;
  }
}
